@echo off

SET MUMBLE_PREFIX=%~dp0
IF %MUMBLE_PREFIX:~-1%==\ SET MUMBLE_PREFIX=%MUMBLE_PREFIX:~0,-1%
SET MUMBLE_PREFIX_BUILD=%MUMBLE_PREFIX%.build

SET VSVER=10.0
SET LIB=

set MUMBLE_OPENSSL_PREFIX=%MUMBLE_PREFIX%\OpenSSL
set MUMBLE_SNDFILE_PREFIX=%MUMBLE_PREFIX%\sndfile
set MUMBLE_PROTOBUF_PREFIX=%MUMBLE_PREFIX%\protobuf
SET MUMBLE_QT_PREFIX=%MUMBLE_PREFIX%\Qt4.8
SET MUMBLE_ICE_PREFIX=%MUMBLE_PREFIX%\ZeroC-Ice

CALL "%DXSDK_DIR%\Utilities\bin\dx_setenv.cmd" x86

IF DEFINED %PROGRAMFILES(X86)% (
  GOTO amd64
) ELSE (
  GOTO x86
)

:amd64
SET PROGPATH=%PROGRAMFILES(X86)%
GOTO Common

:x86
SET PROGPATH=%PROGRAMFILES%
GOTO Common

:Common
CALL "%PROGPATH%\Microsoft Visual Studio %VSVER%\VC\vcvarsall.bat" x86
SET PATH=%MUMBLE_QT_PREFIX%\bin;%MUMBLE_OPENSSL_PREFIX%\bin;%MUMBLE_OPENSSL_PREFIX%\bin;%MUMBLE_PROTOBUF_PREFIX%\vsprojects\Release;%MUMBLE_ICE_PREFIX%\bin;%PATH%
TITLE Mumble Development Environment

cmd /V:ON /K %*
exit /b